name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [
          { target: 'Android', os: 'ubuntu-latest' },
          { target: 'iOS'    , os: 'macos-latest'  }
        ]
    name: Build as ${{ matrix.config.target }} target (${{ matrix.config.os }})
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            gradle/*.versions.toml
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: true
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Android SDK
        if: ${{ matrix.config.target }} == 'Android' && ${{ matrix.config.os }} == 'ubuntu-latest'
        uses: android-actions/setup-android@v3
      - name: Setup Xcode
        if: ${{ matrix.config.target }} == 'iOS' && ${{ matrix.config.os }} == 'macos-latest'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build app for ${{ matrix.config.target }}
        run: |
          if   [[ "${{ matrix.config.target }}" == "Android" && "${{ matrix.config.os }}" == "ubuntu-latest" ]]; then
              ./gradlew :android:assembleDebug
          elif [[ "${{ matrix.config.target }}" == "iOS"     && "${{ matrix.config.os }}" == "macos-latest"  ]]; then
              cd iosApp
              xcodebuild               \
                  -scheme iosApp       \
                  -configuration Debug \
                  -destination ' \
                      platform=iOS Simulator,   \
                      OS=latest,name="iPhone 8" \
                  ' \
                  CODE_SIGNING_ALLOWED='NO'
          fi
